from phi.agent import Agent
from phi.model.groq import Groq
from phi.tools.yfinance import YFinanceTools
from phi.tools.duckduckgo import DuckDuckGo
import openai

import os
from dotenv import load_dotenv
load_dotenv()
openai.api_key=os.getenv("OPEN_API_KEY")

##web search agent
web_search_agent=Agent(
    name="web search agent",
    role="search the web for the information",
    model=Groq(id="llama-3.2-11b-vision-preview"),
    tools=[DuckDuckGo()],
    instructions=["Always include sources"],
    show_tools_calls=True,
    markdown=True,
    
)

##financial agent

finance_agent=Agent(
    name="Financial  AI Agent",
    model=Groq(id="llama-3.2-11b-vision-preview"),
   tools=[YFinanceTools(stock_price=True, analyst_recommendations=True, stock_fundamentals=True,
                        company_news=True),],
   instructions=["use tables to dispaly the data"],
   show_tools_calls=True,
   markdown=True,
    
)

multi_ai_agent=Agent(
    team=[web_search_agent,finance_agent],
    instructions=["Always include sources" ,"use tables to dispaly the data"],
    show_tools_calls=True,
    markdown=True,
    
    
)
    

multi_ai_agent.print_response("Summarize analyst recommendation and share the latest news for NVDIA",stream=True)














